services:
  caddy:
    container_name: caddy
    image: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
  api:
    container_name: directus
    image: directus/directus
    volumes:
      - './ca.pem:/directus/ca.pem'
    env_file:
      - '.env'
    ports:
      - "8055:8055"
